name: Release

on:
  push:
    branches:
      - master
      - feature
    paths:
      - "src/AutoMapper/**" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Build Project
        run: dotnet build src/AutoMapper/AutoMapper.csproj --configuration Release

      - name: Pack NuGet Package
        run: dotnet pack src/AutoMapper/AutoMapper.csproj --configuration Release --output ./nupkgs

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
